variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "zone" {}
variable "project_name" {}
variable "database_name" {}
variable "ecs_password" {}
variable "db_user" {}
variable "db_password" {}
